### ISSUE TITLE
Минифицированный js

### ISSUE THREAD

**Issue by yelizariev** [ITLibertas/odoo-public-addons#1]
Почему бы не использовать оригинальный файл 
https://github.com/ITLibertas/odoo-public-addons/blob/master/web_kladr_widget/__openerp__.py#L14

Odoo вроде как сама все минифицирует.

**Comment by barachka** [comment]
Да, Odoo сама умеет. В тот момент было проще использовать минифицированый, по привычке. Переделаем.
